---
title: "NACI Data Cleaning"
author: "Tommy J. Flynn"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

## two 

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(naniar) # for missing data
library(lubridate)
library(vtable)# good package for summary tables
library(haven)
# directory path
rdata_dir <- "/Users/tommy-two/Documents/1_Research/2_Data_Science/0_Projects/1_NACI/Data/Rdata"
rdata_archive <- paste0(rdata_dir, "/rds_archive")
```


```{r all_pts}
pts_pop2 <- read_sas("Data/patients/patients_population2.sas7bdat")
population_pts_demographics <- read_csv("Data/patients/Population_Patient_Demographics.csv")
pop_pts <- population_pts_demographics %>% 
  mutate(med_rec_no = as.character(`Medical Record Number`),
         encounter_no = as.character(`Enc .`),
         arrival_dt = mdy(`ED Arrival Timestamp`),
         departure_dt = mdy(`ED Departure Timestamp`),
         arrival_mode = as_factor(`Arr Mode`),
         acuity = as_factor(Acuity),
         chief_complaint = `Chief Complaint`,
         age = `Patient Age at Visit`,
         sex = Sex,
         race = Race,
         disposition = `ED Disposition`,
         `% ED Patients Admitted as Inpt or Obs` = NULL,
         .keep = "unused")


all_pts <- all_pts %>% 
  select(-encounter_no2) %>% 
  nrow()

```

```{r all_staff}
all_staff <- read_rds("all_staff.Rdata")
str(all_staff)
# use `jobtitle` (which includes "RN?" observations) to make
all_staff %>% 
  mutate(staff_category = if_else(jobtitle == "RN?", "RN", as.character(jobtitle))) %>% 
  glimpse() 
```

