---
title: Racialized Network Structures of Clinical Interactions in the ED
author:
  - name: Tommy Flynn
    email: tommy.flynn@emory.edu
    affiliation: Emory University
    footnote: 1
  - name: Kate Yeager
    email: kyeager@emory.edu
    affiliation: Emory University
  - name: Ymir Vigfusson
    email: ymir@emory.edu
    affiliation: Emory University
  - name: David Wright
    email: david.wright@emory.edu
    affiliation: Emory University
  - name: Dian Evans
    email: dian.evans@emory.edu
    affiliation: Emory University
  - name: Vicki Hertzberg
    email: vhertzberg@emory.edu
    affiliation: Emory University
address:
  - code: Emory University
    address: 1520 Clifton Rd, Atlanta, GA, 30322
footnote:
  - code: 1
    text: "Corresponding Author"
abstract:  |
  Network science methodologies offer unique opportunities to study real-world human interactions in diverse contexts. The emergency department (ED) is a complex dynamic environment in which clinical care and patient experience depend on the quality of clinician-patient and clinician-clinician encounters, or clinical interactions. Clinical interactions (CIs) are multidimensional social phenomena embedded at the center of healthcare services and one of the primary pathways thought to cause racial healthcare disparities. Evidence of racial disparities in the quality of care provided to Black patients compared to White patients in U.S. EDs is strong. One roadblock to understanding social and clinical mechanisms is the need for research methods suited for dynamic complexity inherent to clinical interactions in the ED. The purpose of this study is to describe a network analysis of clinical interactions (NACI) and the effects of patient race on structural network variables in an urban ED in the Southern United States. We conducted a secondary analysis of observational clinical data to describe how patients’ racial affiliations relate to CI network structures. Network data were generated passively with radiofrequency identification (RFID) tags worn by patients and clinicians during their time in the ED. Clinical interactions were measured as RFID tag proximity within 1 m. Patient demographic and clinical data points were gathered from medical records.  
  
journal: "International Journal of Nursing Studies"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
linenumbers: true
numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
---

```{r Setup}
# knitr::options(root.dir = paste0(getwd(), ""))
```



Understanding healthcare disparities is an ongoing research priority for leading institutions and universities in the United States. Network science draws on the perspectives, philosophies, and methods of various qualitative and quantitative research traditions to understand relationships between objects embedded in complex systems. Focusing a network science lens on clinical interactions in the complex ED environment may add to current evidence of patient-clinician dimensions of racial healthcare disparities. __The purpose of this paper is to report a secondary data analysis of clinical interactions in the Emergency Department of a large academic hospital in the Southern U.S. using social network analyses of ED clinical interactions between patients and healthcare personnel.__

We report a secondary analysis of longitudinal ED contact network data. Data were collected previously with a prospective observational design at an academic urban ED in Atlanta, Georgia.
_Finding Meaning in Social Network Structure_  
The meaning of network structures depends on researchers’ decisions about how to define individual actors (i.e., nodes) and their inter-relational connections (i.e., ties). In fact, the research question under investigation is considered the guiding force behind conceptual and operational interpretations of networks. For example, consider network data generated by a novel contact tracing app designed to track viral exposures in a given population. This hypothetical network data would consist of individuals at risk of exposure (nodes), proximity to other nodes (ties), and exposure status (attribute). As node nj’s number of social contacts (degree centrality) increase, nj’s risk of exposure increases. As more attribute data are available, say vaccination status, the meanings of network structures (e.g., degree centrality) are reconsidered. When studying ED network data, we can assume that a tie between patient and clinician nodes is a part of service delivery: specifically, a patient-clinician interactions (i.e., clinical interactions). In some healthcare settings, clinical interactions are the building blocks of clinical relationships with broader implications for quality and equity. Clinical relationships are, however, beyond the purview of this paper. By defining network connections as clinician-patient interactions, its centrality is a measure of–at the least–quantity of direct clinical care, and–we hypothesize–important dimensions of quality clinical care like clinician-patient communication, changes in patient acuity, and ED throughput.  

_Passive Location Collection with Radiofrequency Identification (RFID)_  
RFID systems are used in a number of hospitals nationwide [@RN364], commonly for supply chain management, passive patient identification, safe medication administration, patient tracking, and asset tracking [@RN257]. RFID systems consist of small tags or badges that emit radio-frequencies that are picked up by sensors located strategically so that every RFID badge is always identifiable to at least 3 sensors for location by triangulation [@RN257]. The presence of RFID-enabled healthcare facilities nationwide will allow for replication of this research, and the evaluation of equity improvement interventions can be done with some minor alterations to existing hardware. Compared to other technologies used for locating resources, the inexpensive and unobtrusive design of RFID tags make them ideal for healthcare applications. Additionally, person-to-person proximity data, such as ours, is likely the most informative sensor-generated data for mapping and studying human networks [@RN259].  
<center>
__Method__  
</center>  
This secondary analysis and its parent study independently received ethics approval by institutional review board. Sampling strategy and data collection methods were described previously [@RN1]
_Sampling_   
Sampling strategies in network research are defined by the purpose of the research at hand.[@RN150] Sample size calculations have not yet been developed for a study designed to compare the networks of various individuals. In addition, most network analysis research to date does not use random sampling, instead often describing entire populations [@RN150]. When studying networks, sampling is more concerned with defining the bounds of the network and the nature of the relationships between nodes [@RN150] The data were collected with a random sampling of one day shift and one night shift from a single academic urban ED every week over the course of one year. A total of 104 shifts of data were collected for the original study [@RN1]. The sampling strategy was selected to minimize sampling bias related to seasonal or weekly fluctuations in census, acuity, and ED staffing changes [@RN1]. Due to various technical complications and personnel issues during the year, data from a number of shifts scheduled for data collection were deemed inadequate for analyses. 81 12-hours shifts were available for the current study.



References {#references .unnumbered}
==========
